chore: Removes documentation from README and link to docs on Charmhub instead
canonical/route53-lego-k8s-operator pull request #66
Opened 2024-02-23 11:58 UTC by saltiyazan

# Description

Improves the README, metadata and config files

Note for reviewers:
Please take a look at the enhanced docs in Charmhub:
- https://discourse.charmhub.io/t/route53-lego-operator-k8s-docs-index/12514

# Checklist:

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [x] I validated that new and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have bumped the version of the library

2024-02-23 15:20 UTC, ghislainbourgeois requested changes
Looks good, but I would not use all caps for the name of the service. Amazon uses the capitalization I suggested.

2024-02-23 15:20 UTC, ghislainbourgeois commented on README.md
> +using [AMAZON ROUTE 53](https://go-acme.github.io/lego/dns/route53/) plugin and the DNS-01 challenge.
```suggestion
using [Amazon Route 53](https://go-acme.github.io/lego/dns/route53/) plugin and the DNS-01 challenge.
```

2024-02-23 15:20 UTC, ghislainbourgeois commented on metadata.yaml
> +  using AMAZON ROUTE 53 plugin and the DNS-01 challenge.
```suggestion
  using Amazon Route 53 plugin and the DNS-01 challenge.
```

2024-02-23 15:20 UTC, ghislainbourgeois commented on metadata.yaml
> +  using AMAZON ROUTE 53 plugin and the DNS-01 challenge.
```suggestion
  using Amazon Route 53 plugin and the DNS-01 challenge.
```

2024-02-23 15:48 UTC, gruyaume commented
> Looks good, but I would not use all caps for the name of the service. Amazon uses the capitalization I suggested.

Unless you want to yell it loudly...

2024-02-26 09:42 UTC, Kayra1 approved these changes

2024-02-26 16:18 UTC, ghislainbourgeois approved these changes

2024-02-27 05:34 UTC, merged